### ISSUE TITLE
Travis: Use job names

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zemeroth#372]
At the moment [I'm using ad-hoc job naming with dummy env variables](https://github.com/ozkriff/zemeroth/blob/e003bf8f438a75fa27dfd789a8eaa219c113e1e2/.travis.yml#L48-L68):

```yaml
  - env: FEATURE=fmt
    rust: nightly-2018-10-01
    install:
      - rustup component add rustfmt-preview
      - rustfmt -V
    script:
      - cargo fmt --all -- --check
```

But now travis actually supports real names for jobs:

https://docs.travis-ci.com/user/customizing-the-build/#naming-jobs-within-matrices

_(Learned about this Travis feature [here](https://www.reddit.com/r/rust/comments/9ndo5k/travis_ci_now_supports_testing_windows_includes/e7lhyjg/))_
